version: '3'
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:5000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:80
    # links:
    #   - backend
